name: Run Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v2
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel
          pip install '.[testing]'
      - name: Run mypy
        run: |
          mypy --install-types --non-interactive ./{{ cookiecutter.module_name }}
      - name: Run pytest
        run: |
          pytest
      - name: Run flake8
        run: |
          flake8 ./{{ cookiecutter.module_name }}
